// WARNING: deletes all existing skills first
// SEED SCRIPT

require("dotenv").config();
const connectToDatabase = require("./db");
const Skill = require("./models/Skill");

async function seed() {
  await connectToDatabase();
  await Skill.deleteMany({});

  await Skill.insertMany([
    // SEEKER BRANCH
    {
      skillId: "s1a",
      branch: "seeker",
      tier: 1,
      label: "Artefact Eye",
      description: "Give hints towards puzzles",
      icon: "visibility_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "s1b",
      branch: "seeker",
      tier: 1,
      label: "Double Harvest",
      description: "Doubles the exp got",
      icon: "auto_awesome_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "s2a",
      branch: "seeker",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "s2b",
      branch: "seeker",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "s2c",
      branch: "seeker",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "s3a",
      branch: "seeker",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "s3b",
      branch: "seeker",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },

    // TRAILBLAZER BRANCH
    {
      skillId: "t1a",
      branch: "trailblazer",
      tier: 1,
      label: "Gotta Go Fast",
      description: "Freezes time for 5 hours",
      icon: "timer_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "t1b",
      branch: "trailblazer",
      tier: 1,
      label: "Double Harvest",
      description: "Doubles the exp got",
      icon: "auto_awesome_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "t2a",
      branch: "trailblazer",
      tier: 2,
      label: "Runner's Eye",
      description: "Increase quest decision radius",
      icon: "directions_run_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "t2b",
      branch: "trailblazer",
      tier: 2,
      label: "Skip Token",
      description: "Skip a task in a quest",
      icon: "skip_next_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "t2c",
      branch: "trailblazer",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "t3a",
      branch: "trailblazer",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "t3b",
      branch: "trailblazer",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },

    // WANDERER BRANCH
    {
      skillId: "w1a",
      branch: "wanderer",
      tier: 1,
      label: "Double Harvest",
      description: "Doubles the exp got",
      icon: "auto_awesome_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "w1b",
      branch: "wanderer",
      tier: 1,
      label: "Need More",
      description: "One more additional SP for level up",
      icon: "add_circle_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "w2a",
      branch: "wanderer",
      tier: 2,
      label: "Explorer's Eye",
      description: "Increase quest decision radius",
      icon: "explore_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "w2b",
      branch: "wanderer",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "w2c",
      branch: "wanderer",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "w3a",
      branch: "wanderer",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "w3b",
      branch: "wanderer",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },

    // PRIME BRANCH
    {
      skillId: "p1a",
      branch: "prime",
      tier: 1,
      label: "Double Harvest",
      description: "Doubles the exp got",
      icon: "auto_awesome_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "p1b",
      branch: "prime",
      tier: 1,
      label: "Need More",
      description: "One more additional SP for level up",
      icon: "add_circle_rounded",
      state: "available",
      skillPoint: 1,
    },
    {
      skillId: "p2a",
      branch: "prime",
      tier: 2,
      label: "Broker's Eye",
      description: "Reduces the cost of cosmetics by 0.15",
      icon: "storefront_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "p2b",
      branch: "prime",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "p2c",
      branch: "prime",
      tier: 2,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "p3a",
      branch: "prime",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
    {
      skillId: "p3b",
      branch: "prime",
      tier: 3,
      label: "TBA",
      description: "TBA",
      icon: "lock_rounded",
      state: "locked",
      skillPoint: 1,
    },
  ]);

  console.log("Skills seeded!");
  process.exit(0);
}

seed().catch(console.error);
